#/--------------------------------------------------------------------------------------------------
#/   _     ___    __
#/  | |__ /'v'\  / /    \date        2021-09-20
#/  | / /(     )/ _ \   \copyright   2021 Sorbonne University https://opensource.org/licenses/MIT
#/  |_\_\ x___x \___/
#/
#/--------------------------------------------------------------------------------------------------

clean:
	make -C 1_hello_boot clean
	make -C 2_init_asm   clean
	make -C 3_init_c     clean
	make -C 4_nttys      clean
	make -C 5_driver     clean
